--- 
spring: 
  application: 
    name: customerService
  datasource: 
    driverClassName: com.mysql.jdbc.Driver
    max-active: 15
    max-idle: 10
    max-wait: 8000
    password: root
    testOnBorrow: true
    testWhileIdle: true
    url: "jdbc:mysql://google/MyService?cloudSqlInstance=mysql-gcp:us-central1:gcp-cloud&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=root&password=&useSSL=false"
    userName: root
    validationQuery: "SELECT 1"
management:
  security:
    enabled: false